image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache curl jq python3 python3-dev git
  - pip3 install awscli
  - pip3 install awsebcli

stages:
  - mirror
  - test
  - build

mirror:
  stage: mirror
  script:
    - git push --mirror https://sourcepirate:$GPASS@github.com/sourcepirate/tdd-jasmine.git

test:
  stage: test
  script:
    - pip3 install -r demo/requirements.txt
    - cd demo/
    - python3 manage.py test --verbosity 3 --failfast

build:
  stage: build
  script:
    - docker login registry.gitlab.com --username $USERNAME --password $PASSWORD
    - export VERSION=$(date +%s)
    - docker build -t registry.gitlab.com/sourcepirate/django-rds-demo:$VERSION $PWD
    - docker push registry.gitlab.com/sourcepirate/django-rds-demo:$VERSION
  only:
    - master
  tags:
    - docker
