image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - pip install awsebcli

stages:
  - test
  - build

test:
  stage: test
  script:
    - pip install -r demo/requirements.txt
    - cd demo/
    - python manage.py test --verbosity 3 --failfast

build:
  stage: build
  script:
    - docker login registry.gitlab.com --username $USERNAME --password $PASSWORD
    - export VERSION=$(date +%s)
    - docker build -t registry.gitlab.com/sourcepirate/django-rds-demo:$VERSION .
    - docker push registry.gitlab.com/sourcepirate/django-rds-demo:$VERSION
  only:
    - master
  tags:
    - docker
